# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vanotblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: Jiang123
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
server:
  port: 80

